name: Go

on:
  push:
    branches: ["main", "development"]

  pull_request:
    branches: ["main", "development"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install raylib dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            pkg-config \
            libgl1-mesa-dev \
            libwayland-dev \
            libwayland-bin \
            wayland-protocols \
            libxkbcommon-dev \
            libx11-dev \
            libxcursor-dev \
            libxinerama-dev \
            libxrandr-dev \
            libxi-dev \
            libxxf86vm-dev \
            libxfixes-dev \
            libasound2-dev

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Build
        run: go build -v ./...

      - name: Run Unit Tests
        run: go test -v ./...

      - name: Run go vet
        run: go vet ./...
